name: Build V2Ray

on:
  release:
    types: [prereleased]
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        # Include amd64 on all platforms.
        goos: [windows, freebsd, openbsd, linux, dragonfly, darwin]
        goarch: [amd64, 386]
        exclude:
          # Exclude i386 on darwin and dragonfly.
          - goarch: 386
            goos: dragonfly
          - goarch: 386
            goos: darwin
        include:
          # BEGIN Linux ARM 5 6 7
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: arm
            goarm: 6
          - goos: linux
            goarch: arm
            goarm: 5
          # END Linux ARM 5 6 7
          # Windows ARM 7
          - goos: windows
            goarch: arm
            goarm: 7
          # BEGIN Other architectures
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: riscv64
          # BEGIN MIPS
          - goos: linux
            goarch: mips64
          - goos: linux
            goarch: mips64le
          - goos: linux
            goarch: mipsle
          - goos: linux
            goarch: mips
          # END MIPS
          # END Other architectures
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Show Workflow Information
        id: get_filename
        run: |
          export _NAME=$(jq ".[\"$GOOS-$GOARCH$GOARM\"].friendlyName" -r < release/friendly-filenames.json)
          echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: $GOARM, RELEASE_NAME: $_NAME"
          echo "::set-output name=ASSET_NAME::$_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Get project dependencies
        run: go mod download

      - name: Build V2Ray
        run: |
          mkdir build_assets
          go build -v -o build_assets/v2ray -trimpath -ldflags "-s -w -buildid=" ./main
          go build -v -o build_assets/v2ctl -trimpath -ldflags "-s -w -buildid=" -tags confonly ./infra/control/main

      - name: Build Windows wv2ray
        if: matrix.goos == 'windows'
        run: |
          go build -v -o build_assets/wv2ray.exe -trimpath -ldflags "-s -w -H windowsgui -buildid=" ./main
          cd ./build_assets
          mv ./v2ray ./v2ray.exe
          mv ./v2ctl ./v2ctl.exe

      - name: Prepare Package
        run: cp -v ./release/config/*.* ./build_assets

      - name: Prepare Package for Linux
        if: matrix.goos == 'linux'
        run: cp -rv ./release/config/systemd ./build_assets/

      - name: Creating ZIP Archive
        run: |
          cd ./build_assets
          ls -lah .
          zip -9vr ./v2ray-$ASSET_NAME.zip .
          mv -v ./v2ray-$ASSET_NAME.zip ../v2ray-$ASSET_NAME.zip
          cd .. && pwd && ls -lah

      - uses: actions/upload-artifact@v2
        with:
          name: v2ray-${{ steps.get_filename.outputs.ASSET_NAME }}.zip
          path: v2ray-${{ steps.get_filename.outputs.ASSET_NAME }}.zip

      - name: Upload to release
        uses: svenstaro/upload-release-action@v1-release
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: v2ray-${{ steps.get_filename.outputs.ASSET_NAME }}.zip
          asset_name: v2ray-${{ steps.get_filename.outputs.ASSET_NAME }}.zip
          tag: ${{ github.ref }}
          overwrite: true

  signature:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/download-artifact@v2
        with:
          path: build_artifacts

      - name: Generate Hash
        run: |
          cd build_artifacts
          ls -lah --recursive
          {
            go run github.com/v2fly/V2BuildAssist/v2buildutil gen version $(git describe --tags)
            go run github.com/v2fly/V2BuildAssist/v2buildutil gen project "v2fly"
            for zip in $(find -L . -type f -name "*.zip"); do
              go run github.com/v2fly/V2BuildAssist/v2buildutil gen file ${zip}
            done
          } >Release.unsigned.unsorted
          # Generate Release.unsigned file
          go run github.com/v2fly/V2BuildAssist/v2buildutil gen sort < Release.unsigned.unsorted > Release.unsigned
          rm -f Release.unsigned.unsorted
          cat ./Release.unsigned
